### ISSUE TITLE
magento2:generate:command - Could not find CommandList node

### ISSUE THREAD

**Issue by uabassguy** [astorm/pestle#182]
Hello, I tried to generate a command using pestle and encountered the following error after being prompted for 'Command Name? (Testbed)]'

> PHP Fatal error:  Uncaught Exception: Could not find CommandList node in phar:///vagrant/pestle.phar/modules/pulsestorm/magento2/cli/generate/command/module.php:78
> Stack trace:
> #0 phar:///vagrant/pestle.phar/modules/pulsestorm/magento2/cli/generate/command/module.php(98): Pulsestorm\Magento2\Cli\Generate\Command\pestle_cli(Array)
> #1 [internal function]: Pulsestorm\Magento2\Cli\Generate\Command\exported_pestle_cli(Array)
> #2 /tmp/pestle_cache/2d27f575ea4837c003f8467c72c32131/reflection-strategy/d35297206a0d27b48969861d55e34abe.php(7): ReflectionFunction->invokeArgs(Array)
> #3 phar:///vagrant/pestle.phar/modules/pulsestorm/magento2/cli/magento2/generate/command/module.php(24): exported_pestle_cli(Array)
> #4 [internal function]: Pulsestorm\Magento2\Cli\Magento2\Generate\Command\pestle_cli(Array, Array)
> #5 phar:///vagrant/pestle.phar/modules/pulsestorm/pestle/runner/module.php(366): ReflectionFunction->invokeArgs(Array)
> #6 /vagrant/pestle.phar(7): Pulsestorm\Pestle\Runner\main(Array)
> #7 /vagrant/pestle.phar(9): main(Array)
> #8 {main}
>  in phar:///vagrant/pestle.phar/modules/pulsestorm/magento2/cli/generate/command/module.php on line 78

**Comment by astorm** [comment]
Thanks for the bug report @uabassguy!  Looking over the pestle code, I think I see the problem.  We wrote this with the assumption that 

1. Our command created your `di.xml`
2. The module you're trying to create this in doesn't have a `di.xml`

I'm guessing that you're trying to create a command in a module that already has a `di.xml`?  If so that's a clear bug on our part.    While we work on a more permanent fix, as a work around, if you manually add the following `type` node to your di.xml file

    <config xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="urn:magento:framework:ObjectManager/etc/config.xsd">
        
        <type name="Magento\Framework\Console\CommandList"></type>
        
    </config>

you should be able to use the pestle command.

Also, if possible, could you share your `di.xml` file?  Working against actual files from the real world tends to lead to better results for us.  If you can't (private project, etc.) no worries, we'll still work to get a fix out.

**Comment by uabassguy** [comment]
Ah you're right, there is a di.xml, I wish I could share it but yes, it is a private project for a company. I'll add the line to the xml. Thanks for the awesome tool! It definitely helps a ton

**Comment by astorm** [comment]
@uabassguy Just pushed an update that should take care of this -- run

    pestle.phar selfupdate

and give it a try.  If you're still seeing a problem just let us know.
