### ISSUE TITLE
magento2:generate:ui:grid Collection model name does not conform to the arbitrary naming convention we chose

### ISSUE THREAD

**Issue by ddoddsr** [astorm/pestle#213]
Ran `pestle.phar magento2:generate:ui:grid` with defaults:
```
What Resource Collection Model should your listing use? (Magento\Cms\Model\ResourceModel\Page\Collection)] 
... ...
Collection model name does not conform to the arbitrary naming convention we chose.  We're bailing.
```
In module.php and in all.php we have this test `if($parts[3] !== 'ResourceModel' || $parts[(count($parts)-1)])`
Not sure what we are testing for in the 2nd half.
Is it intended that the last part of the collection model name is "**Collection**" ?
Something like `if($parts[3] !== 'ResourceModel' || $parts[(count($parts)-1)]) !== 'Collection'`

**Comment by astorm** [comment]
Thanks @ddoddsr, that's definitely a bug, and a double one at that.  We didn't actually bail from the command due to a misnamed collection class **and** we didn't have the right code in the `if` statement.  Both are fixed, and should be a part of the next release.  Take a look, and if you still have questions let us know!
