### ISSUE TITLE
List command doesnt work

### ISSUE THREAD

**Issue by woutersamaey** [astorm/pestle#271]
I followed the getting started steps, and got an error right away:

curl -LO http://pestle.pulsestorm.net/pestle.phar
php pestle.phar list

Can't find [list_commands] in Pulsestorm\Pestle\Runner\includeLibraryForCommand

**Comment by ddoddsr** [comment]
Try pestle list-commands.

**Comment by astorm** [comment]
@woutersamaey Our apologies -- we recently did some refactoring last month and  broke some commands along the way.  The issue you've mentioned has been fixed in the master branch and will go in the next point release. (details here https://github.com/astorm/pestle/issues/121).

In the meanwhile, you can use any of the following to get a list of the commands

    pestle.phar
    pestle.phar list
    pestle.phar list-commands
    pestle.phar list_commands

Yes -- even `pestle.phar list_commands` works, despite the error you're seeing when you try to run `list` (it was/is a weird error).

Also, if you have a moment -- was there a particular page on the internet where you saw `pestle.phar list` used?  We'd like to change that so someone else doesn't run into the same problem until our next point release. 

Thanks for giving pestle a try -- I hope this first experience doesn't sour you to what it can offer!

**Comment by astorm** [comment]
OK -- we've got the main README fixed thanks to @ddoddsr and, per previous comments, the next point release will feature a fix.  

@woutersamaey if you found `list` somewhere other than the main README please feel free to reopen and comment to let us know.  Thanks again for reporting the issue -- it's bug reports like yours that help keep pestle moving forward.
