### ISSUE TITLE
db_schema.xml

### ISSUE THREAD

**Issue by timsayshey** [astorm/pestle#521]
I'm new to Magento but aren't best practices to use db_schema.xml instead of InstallSchema.php? If that is the case why is this tool generating InstallSchema.php?

**Comment by astorm** [comment]
Magento introduced the `db_schema.xml` feature in Magento 2.3.  Whether it's a "best practice" or not to use this feature depends on the version(s) of Magento you're targeting.

Pestle generates `InstallSchema` scripts because pestle predates Magento 2.3, and because no one's been passionate enough about a `db_schema.xml` generator to add one to pestle.

Closing this out as answered, but if you have follow up questions don't hesitate to bring them up.
